export const defaultConfig = {
  defaultEnvironment: 'local',
  applicationName: 'Performance Management Application',
  port: 9000,
  loggerRootName: 'server',
  loggerDefaultLevel: 'info' as keyof typeof NodeJS.LogLevel,
  loggerDefaultTheme: 'DefaultTheme',
  oidcGroupFiltersRegex: [/GG-UK-TescoGlobal-(-[\w\d]+)+/],
  applicationCookieParserSecret: 'tesco.pma.cookie.secret',
  applicationUserDataCookieName: 'tesco.pma.userinfo',
  cacheIdentityTokenKey: 'application.scope.identity.token',
  authPath: '/auth',
  buildPath: 'build',
  mfModule: 'tesco-pma.js',
  SSOLogoutPath: '/sso/logout',
  oidcAuthCallbackPath: '/sso/auth/callback',
  oidcRedirectAfterLogoutPath: '/sso/logout/callback',
};
