/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { ErrorDetail, ErrorDetailFromJSON, ErrorDetailFromJSONTyped, ErrorDetailToJSON } from './';

/**
 *
 * @export
 * @interface ApiError
 */
export interface ApiError {
  /**
   *
   * @type {string}
   * @memberof ApiError
   */
  code?: string;
  /**
   *
   * @type {string}
   * @memberof ApiError
   */
  message?: string;
  /**
   *
   * @type {string}
   * @memberof ApiError
   */
  target?: string;
  /**
   *
   * @type {Array<ErrorDetail>}
   * @memberof ApiError
   */
  details?: Array<ErrorDetail>;
}

export function ApiErrorFromJSON(json: any): ApiError {
  return ApiErrorFromJSONTyped(json, false);
}

export function ApiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiError {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    code: !exists(json, 'code') ? undefined : json['code'],
    message: !exists(json, 'message') ? undefined : json['message'],
    target: !exists(json, 'target') ? undefined : json['target'],
    details: !exists(json, 'details') ? undefined : (json['details'] as Array<any>).map(ErrorDetailFromJSON),
  };
}

export function ApiErrorToJSON(value?: ApiError | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    code: value.code,
    message: value.message,
    target: value.target,
    details: value.details === undefined ? undefined : (value.details as Array<any>).map(ErrorDetailToJSON),
  };
}
