/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  Colleague,
  ColleagueFromJSON,
  ColleagueFromJSONTyped,
  ColleagueToJSON,
  TypedAttribute,
  TypedAttributeFromJSON,
  TypedAttributeFromJSONTyped,
  TypedAttributeToJSON,
} from './';

/**
 *
 * @export
 * @interface ColleagueProfile
 */
export interface ColleagueProfile {
  /**
   *
   * @type {Colleague}
   * @memberof ColleagueProfile
   */
  colleague?: Colleague;
  /**
   *
   * @type {Array<TypedAttribute>}
   * @memberof ColleagueProfile
   */
  profileAttributes?: Array<TypedAttribute>;
}

export function ColleagueProfileFromJSON(json: any): ColleagueProfile {
  return ColleagueProfileFromJSONTyped(json, false);
}

export function ColleagueProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColleagueProfile {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    colleague: !exists(json, 'colleague') ? undefined : ColleagueFromJSON(json['colleague']),
    profileAttributes: !exists(json, 'profileAttributes')
      ? undefined
      : (json['profileAttributes'] as Array<any>).map(TypedAttributeFromJSON),
  };
}

export function ColleagueProfileToJSON(value?: ColleagueProfile | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    colleague: ColleagueToJSON(value.colleague),
    profileAttributes:
      value.profileAttributes === undefined
        ? undefined
        : (value.profileAttributes as Array<any>).map(TypedAttributeToJSON),
  };
}
