/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ContractType
 */
export interface ContractType {
  /**
   *
   * @type {string}
   * @memberof ContractType
   */
  sourceCode?: string;
  /**
   *
   * @type {string}
   * @memberof ContractType
   */
  sourceName?: string;
  /**
   *
   * @type {Date}
   * @memberof ContractType
   */
  endDate?: Date;
}

export function ContractTypeFromJSON(json: any): ContractType {
  return ContractTypeFromJSONTyped(json, false);
}

export function ContractTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractType {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    sourceCode: !exists(json, 'sourceCode') ? undefined : json['sourceCode'],
    sourceName: !exists(json, 'sourceName') ? undefined : json['sourceName'],
    endDate: !exists(json, 'endDate') ? undefined : new Date(json['endDate']),
  };
}

export function ContractTypeToJSON(value?: ContractType | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    sourceCode: value.sourceCode,
    sourceName: value.sourceName,
    endDate: value.endDate === undefined ? undefined : value.endDate.toISOString().substr(0, 10),
  };
}
