/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { AddressList, AddressListFromJSON, AddressListFromJSONTyped, AddressListToJSON } from './';

/**
 *
 * @export
 * @interface Contact
 */
export interface Contact {
  /**
   *
   * @type {string}
   * @memberof Contact
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof Contact
   */
  workPhoneNumber?: string;
  /**
   *
   * @type {AddressList}
   * @memberof Contact
   */
  addresses?: AddressList;
}

export function ContactFromJSON(json: any): Contact {
  return ContactFromJSONTyped(json, false);
}

export function ContactFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contact {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: !exists(json, 'email') ? undefined : json['email'],
    workPhoneNumber: !exists(json, 'workPhoneNumber') ? undefined : json['workPhoneNumber'],
    addresses: !exists(json, 'addresses') ? undefined : AddressListFromJSON(json['addresses']),
  };
}

export function ContactToJSON(value?: Contact | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    workPhoneNumber: value.workPhoneNumber,
    addresses: AddressListToJSON(value.addresses),
  };
}
