/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Effectivity
 */
export interface Effectivity {
  /**
   *
   * @type {Date}
   * @memberof Effectivity
   */
  from?: Date;
  /**
   *
   * @type {Date}
   * @memberof Effectivity
   */
  to?: Date;
}

export function EffectivityFromJSON(json: any): Effectivity {
  return EffectivityFromJSONTyped(json, false);
}

export function EffectivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Effectivity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    from: !exists(json, 'from') ? undefined : new Date(json['from']),
    to: !exists(json, 'to') ? undefined : new Date(json['to']),
  };
}

export function EffectivityToJSON(value?: Effectivity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    from: value.from === undefined ? undefined : value.from.toISOString().substr(0, 10),
    to: value.to === undefined ? undefined : value.to.toISOString().substr(0, 10),
  };
}
