/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { IamSourceSystem, IamSourceSystemFromJSON, IamSourceSystemFromJSONTyped, IamSourceSystemToJSON } from './';

/**
 *
 * @export
 * @interface ExternalSystems
 */
export interface ExternalSystems {
  /**
   *
   * @type {string}
   * @memberof ExternalSystems
   */
  sourceSystem?: string;
  /**
   *
   * @type {IamSourceSystem}
   * @memberof ExternalSystems
   */
  iam?: IamSourceSystem;
}

export function ExternalSystemsFromJSON(json: any): ExternalSystems {
  return ExternalSystemsFromJSONTyped(json, false);
}

export function ExternalSystemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalSystems {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    sourceSystem: !exists(json, 'sourceSystem') ? undefined : json['sourceSystem'],
    iam: !exists(json, 'iam') ? undefined : IamSourceSystemFromJSON(json['iam']),
  };
}

export function ExternalSystemsToJSON(value?: ExternalSystems | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    sourceSystem: value.sourceSystem,
    iam: IamSourceSystemToJSON(value.iam),
  };
}
