/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GroupObjective
 */
export interface GroupObjective {
  /**
   *
   * @type {string}
   * @memberof GroupObjective
   */
  uuid?: string;
  /**
   *
   * @type {string}
   * @memberof GroupObjective
   */
  businessUnitUuid?: string;
  /**
   *
   * @type {string}
   * @memberof GroupObjective
   */
  performanceCycleUuid?: string;
  /**
   *
   * @type {number}
   * @memberof GroupObjective
   */
  sequenceNumber?: number;
  /**
   *
   * @type {string}
   * @memberof GroupObjective
   */
  title?: string;
  /**
   *
   * @type {number}
   * @memberof GroupObjective
   */
  version?: number;
  /**
   *
   * @type {string}
   * @memberof GroupObjective
   */
  status?: GroupObjectiveStatusEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum GroupObjectiveStatusEnum {
  Draft = 'DRAFT',
  Submitted = 'SUBMITTED',
  Approved = 'APPROVED',
  Rejected = 'REJECTED',
  Completed = 'COMPLETED',
}

export function GroupObjectiveFromJSON(json: any): GroupObjective {
  return GroupObjectiveFromJSONTyped(json, false);
}

export function GroupObjectiveFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupObjective {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: !exists(json, 'uuid') ? undefined : json['uuid'],
    businessUnitUuid: !exists(json, 'businessUnitUuid') ? undefined : json['businessUnitUuid'],
    performanceCycleUuid: !exists(json, 'performanceCycleUuid') ? undefined : json['performanceCycleUuid'],
    sequenceNumber: !exists(json, 'sequenceNumber') ? undefined : json['sequenceNumber'],
    title: !exists(json, 'title') ? undefined : json['title'],
    version: !exists(json, 'version') ? undefined : json['version'],
    status: !exists(json, 'status') ? undefined : json['status'],
  };
}

export function GroupObjectiveToJSON(value?: GroupObjective | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    uuid: value.uuid,
    businessUnitUuid: value.businessUnitUuid,
    performanceCycleUuid: value.performanceCycleUuid,
    sequenceNumber: value.sequenceNumber,
    title: value.title,
    version: value.version,
    status: value.status,
  };
}
