/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface IamSourceSystem
 */
export interface IamSourceSystem {
  /**
   *
   * @type {string}
   * @memberof IamSourceSystem
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof IamSourceSystem
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof IamSourceSystem
   */
  source?: string;
}

export function IamSourceSystemFromJSON(json: any): IamSourceSystem {
  return IamSourceSystemFromJSONTyped(json, false);
}

export function IamSourceSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): IamSourceSystem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    name: !exists(json, 'name') ? undefined : json['name'],
    source: !exists(json, 'source') ? undefined : json['source'],
  };
}

export function IamSourceSystemToJSON(value?: IamSourceSystem | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    name: value.name,
    source: value.source,
  };
}
