/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Job
 */
export interface Job {
  /**
   *
   * @type {string}
   * @memberof Job
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Job
   */
  code?: string;
  /**
   *
   * @type {string}
   * @memberof Job
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Job
   */
  costCategory?: string;
}

export function JobFromJSON(json: any): Job {
  return JobFromJSONTyped(json, false);
}

export function JobFromJSONTyped(json: any, ignoreDiscriminator: boolean): Job {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    code: !exists(json, 'code') ? undefined : json['code'],
    name: !exists(json, 'name') ? undefined : json['name'],
    costCategory: !exists(json, 'costCategory') ? undefined : json['costCategory'],
  };
}

export function JobToJSON(value?: Job | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    code: value.code,
    name: value.name,
    costCategory: value.costCategory,
  };
}
