/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Health, HealthFromJSON, HealthFromJSONTyped, HealthToJSON } from './';

/**
 *
 * @export
 * @interface OverallHealth
 */
export interface OverallHealth {
  /**
   *
   * @type {string}
   * @memberof OverallHealth
   */
  status?: OverallHealthStatusEnum;
  /**
   *
   * @type {string}
   * @memberof OverallHealth
   */
  version?: string;
  /**
   *
   * @type {Array<Health>}
   * @memberof OverallHealth
   */
  component?: Array<Health>;
}

/**
 * @export
 * @enum {string}
 */
export enum OverallHealthStatusEnum {
  Ok = 'Ok',
  Fail = 'Fail',
  Degraded = 'Degraded',
}

export function OverallHealthFromJSON(json: any): OverallHealth {
  return OverallHealthFromJSONTyped(json, false);
}

export function OverallHealthFromJSONTyped(json: any, ignoreDiscriminator: boolean): OverallHealth {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    status: !exists(json, 'status') ? undefined : json['status'],
    version: !exists(json, 'version') ? undefined : json['version'],
    component: !exists(json, 'component') ? undefined : (json['component'] as Array<any>).map(HealthFromJSON),
  };
}

export function OverallHealthToJSON(value?: OverallHealth | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    status: value.status,
    version: value.version,
    component: value.component === undefined ? undefined : (value.component as Array<any>).map(HealthToJSON),
  };
}
