/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Position
 */
export interface Position {
  /**
   *
   * @type {string}
   * @memberof Position
   */
  id?: string;
  /**
   *
   * @type {string}
   * @memberof Position
   */
  code?: string;
  /**
   *
   * @type {string}
   * @memberof Position
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Position
   */
  teamName?: string;
}

export function PositionFromJSON(json: any): Position {
  return PositionFromJSONTyped(json, false);
}

export function PositionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Position {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, 'id') ? undefined : json['id'],
    code: !exists(json, 'code') ? undefined : json['code'],
    name: !exists(json, 'name') ? undefined : json['name'],
    teamName: !exists(json, 'teamName') ? undefined : json['teamName'],
  };
}

export function PositionToJSON(value?: Position | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    code: value.code,
    name: value.name,
    teamName: value.teamName,
  };
}
