/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Profile
 */
export interface Profile {
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  middleName?: string;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof Profile
   */
  gender?: string;
  /**
   *
   * @type {Date}
   * @memberof Profile
   */
  dateOfBirth?: Date;
}

export function ProfileFromJSON(json: any): Profile {
  return ProfileFromJSONTyped(json, false);
}

export function ProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): Profile {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: !exists(json, 'title') ? undefined : json['title'],
    firstName: !exists(json, 'firstName') ? undefined : json['firstName'],
    middleName: !exists(json, 'middleName') ? undefined : json['middleName'],
    lastName: !exists(json, 'lastName') ? undefined : json['lastName'],
    gender: !exists(json, 'gender') ? undefined : json['gender'],
    dateOfBirth: !exists(json, 'dateOfBirth') ? undefined : new Date(json['dateOfBirth']),
  };
}

export function ProfileToJSON(value?: Profile | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    firstName: value.firstName,
    middleName: value.middleName,
    lastName: value.lastName,
    gender: value.gender,
    dateOfBirth: value.dateOfBirth === undefined ? undefined : value.dateOfBirth.toISOString().substr(0, 10),
  };
}
