/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ApiError,
  ApiErrorFromJSON,
  ApiErrorFromJSONTyped,
  ApiErrorToJSON,
  PersonalObjective,
  PersonalObjectiveFromJSON,
  PersonalObjectiveFromJSONTyped,
  PersonalObjectiveToJSON,
} from './';

/**
 *
 * @export
 * @interface RestResponsePersonalObjective
 */
export interface RestResponsePersonalObjective {
  /**
   *
   * @type {boolean}
   * @memberof RestResponsePersonalObjective
   */
  success?: boolean;
  /**
   *
   * @type {PersonalObjective}
   * @memberof RestResponsePersonalObjective
   */
  data?: PersonalObjective;
  /**
   *
   * @type {Array<ApiError>}
   * @memberof RestResponsePersonalObjective
   */
  errors?: Array<ApiError>;
}

export function RestResponsePersonalObjectiveFromJSON(json: any): RestResponsePersonalObjective {
  return RestResponsePersonalObjectiveFromJSONTyped(json, false);
}

export function RestResponsePersonalObjectiveFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RestResponsePersonalObjective {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    success: !exists(json, 'success') ? undefined : json['success'],
    data: !exists(json, 'data') ? undefined : PersonalObjectiveFromJSON(json['data']),
    errors: !exists(json, 'errors') ? undefined : (json['errors'] as Array<any>).map(ApiErrorFromJSON),
  };
}

export function RestResponsePersonalObjectiveToJSON(value?: RestResponsePersonalObjective | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    success: value.success,
    data: PersonalObjectiveToJSON(value.data),
    errors: value.errors === undefined ? undefined : (value.errors as Array<any>).map(ApiErrorToJSON),
  };
}
