/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ApiError,
  ApiErrorFromJSON,
  ApiErrorFromJSONTyped,
  ApiErrorToJSON,
  Subsidiary,
  SubsidiaryFromJSON,
  SubsidiaryFromJSONTyped,
  SubsidiaryToJSON,
} from './';

/**
 *
 * @export
 * @interface RestResponseListSubsidiary
 */
export interface RestResponseListSubsidiary {
  /**
   *
   * @type {boolean}
   * @memberof RestResponseListSubsidiary
   */
  success?: boolean;
  /**
   *
   * @type {Array<Subsidiary>}
   * @memberof RestResponseListSubsidiary
   */
  data?: Array<Subsidiary>;
  /**
   *
   * @type {Array<ApiError>}
   * @memberof RestResponseListSubsidiary
   */
  errors?: Array<ApiError>;
}

export function RestResponseListSubsidiaryFromJSON(json: any): RestResponseListSubsidiary {
  return RestResponseListSubsidiaryFromJSONTyped(json, false);
}

export function RestResponseListSubsidiaryFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RestResponseListSubsidiary {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    success: !exists(json, 'success') ? undefined : json['success'],
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(SubsidiaryFromJSON),
    errors: !exists(json, 'errors') ? undefined : (json['errors'] as Array<any>).map(ApiErrorFromJSON),
  };
}

export function RestResponseListSubsidiaryToJSON(value?: RestResponseListSubsidiary | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    success: value.success,
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(SubsidiaryToJSON),
    errors: value.errors === undefined ? undefined : (value.errors as Array<any>).map(ApiErrorToJSON),
  };
}
