/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ApiError,
  ApiErrorFromJSON,
  ApiErrorFromJSONTyped,
  ApiErrorToJSON,
  GroupObjective,
  GroupObjectiveFromJSON,
  GroupObjectiveFromJSONTyped,
  GroupObjectiveToJSON,
} from './';

/**
 *
 * @export
 * @interface RestResponseListGroupObjective
 */
export interface RestResponseListGroupObjective {
  /**
   *
   * @type {boolean}
   * @memberof RestResponseListGroupObjective
   */
  success?: boolean;
  /**
   *
   * @type {Array<GroupObjective>}
   * @memberof RestResponseListGroupObjective
   */
  data?: Array<GroupObjective>;
  /**
   *
   * @type {Array<ApiError>}
   * @memberof RestResponseListGroupObjective
   */
  errors?: Array<ApiError>;
}

export function RestResponseListGroupObjectiveFromJSON(json: any): RestResponseListGroupObjective {
  return RestResponseListGroupObjectiveFromJSONTyped(json, false);
}

export function RestResponseListGroupObjectiveFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RestResponseListGroupObjective {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    success: !exists(json, 'success') ? undefined : json['success'],
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(GroupObjectiveFromJSON),
    errors: !exists(json, 'errors') ? undefined : (json['errors'] as Array<any>).map(ApiErrorFromJSON),
  };
}

export function RestResponseListGroupObjectiveToJSON(value?: RestResponseListGroupObjective | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    success: value.success,
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(GroupObjectiveToJSON),
    errors: value.errors === undefined ? undefined : (value.errors as Array<any>).map(ApiErrorToJSON),
  };
}
