/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ApiError,
  ApiErrorFromJSON,
  ApiErrorFromJSONTyped,
  ApiErrorToJSON,
  User,
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
} from './';

/**
 *
 * @export
 * @interface RestResponseUser
 */
export interface RestResponseUser {
  /**
   *
   * @type {boolean}
   * @memberof RestResponseUser
   */
  success?: boolean;
  /**
   *
   * @type {User}
   * @memberof RestResponseUser
   */
  data?: User;
  /**
   *
   * @type {Array<ApiError>}
   * @memberof RestResponseUser
   */
  errors?: Array<ApiError>;
}

export function RestResponseUserFromJSON(json: any): RestResponseUser {
  return RestResponseUserFromJSONTyped(json, false);
}

export function RestResponseUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestResponseUser {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    success: !exists(json, 'success') ? undefined : json['success'],
    data: !exists(json, 'data') ? undefined : UserFromJSON(json['data']),
    errors: !exists(json, 'errors') ? undefined : (json['errors'] as Array<any>).map(ApiErrorFromJSON),
  };
}

export function RestResponseUserToJSON(value?: RestResponseUser | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    success: value.success,
    data: UserToJSON(value.data),
    errors: value.errors === undefined ? undefined : (value.errors as Array<any>).map(ApiErrorToJSON),
  };
}
