/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ApiError,
  ApiErrorFromJSON,
  ApiErrorFromJSONTyped,
  ApiErrorToJSON,
  Subsidiary,
  SubsidiaryFromJSON,
  SubsidiaryFromJSONTyped,
  SubsidiaryToJSON,
} from './';

/**
 *
 * @export
 * @interface RestResponseSubsidiary
 */
export interface RestResponseSubsidiary {
  /**
   *
   * @type {boolean}
   * @memberof RestResponseSubsidiary
   */
  success?: boolean;
  /**
   *
   * @type {Subsidiary}
   * @memberof RestResponseSubsidiary
   */
  data?: Subsidiary;
  /**
   *
   * @type {Array<ApiError>}
   * @memberof RestResponseSubsidiary
   */
  errors?: Array<ApiError>;
}

export function RestResponseSubsidiaryFromJSON(json: any): RestResponseSubsidiary {
  return RestResponseSubsidiaryFromJSONTyped(json, false);
}

export function RestResponseSubsidiaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestResponseSubsidiary {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    success: !exists(json, 'success') ? undefined : json['success'],
    data: !exists(json, 'data') ? undefined : SubsidiaryFromJSON(json['data']),
    errors: !exists(json, 'errors') ? undefined : (json['errors'] as Array<any>).map(ApiErrorFromJSON),
  };
}

export function RestResponseSubsidiaryToJSON(value?: RestResponseSubsidiary | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    success: value.success,
    data: SubsidiaryToJSON(value.data),
    errors: value.errors === undefined ? undefined : (value.errors as Array<any>).map(ApiErrorToJSON),
  };
}
