/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ApiError,
  ApiErrorFromJSON,
  ApiErrorFromJSONTyped,
  ApiErrorToJSON,
  User,
  UserFromJSON,
  UserFromJSONTyped,
  UserToJSON,
} from './';

/**
 *
 * @export
 * @interface RestResponseCollectionUser
 */
export interface RestResponseCollectionUser {
  /**
   *
   * @type {boolean}
   * @memberof RestResponseCollectionUser
   */
  success?: boolean;
  /**
   *
   * @type {Array<User>}
   * @memberof RestResponseCollectionUser
   */
  data?: Array<User>;
  /**
   *
   * @type {Array<ApiError>}
   * @memberof RestResponseCollectionUser
   */
  errors?: Array<ApiError>;
}

export function RestResponseCollectionUserFromJSON(json: any): RestResponseCollectionUser {
  return RestResponseCollectionUserFromJSONTyped(json, false);
}

export function RestResponseCollectionUserFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RestResponseCollectionUser {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    success: !exists(json, 'success') ? undefined : json['success'],
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(UserFromJSON),
    errors: !exists(json, 'errors') ? undefined : (json['errors'] as Array<any>).map(ApiErrorFromJSON),
  };
}

export function RestResponseCollectionUserToJSON(value?: RestResponseCollectionUser | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    success: value.success,
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(UserToJSON),
    errors: value.errors === undefined ? undefined : (value.errors as Array<any>).map(ApiErrorToJSON),
  };
}
