/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ApiError,
  ApiErrorFromJSON,
  ApiErrorFromJSONTyped,
  ApiErrorToJSON,
  TypedAttribute,
  TypedAttributeFromJSON,
  TypedAttributeFromJSONTyped,
  TypedAttributeToJSON,
} from './';

/**
 *
 * @export
 * @interface RestResponseListTypedAttribute
 */
export interface RestResponseListTypedAttribute {
  /**
   *
   * @type {boolean}
   * @memberof RestResponseListTypedAttribute
   */
  success?: boolean;
  /**
   *
   * @type {Array<TypedAttribute>}
   * @memberof RestResponseListTypedAttribute
   */
  data?: Array<TypedAttribute>;
  /**
   *
   * @type {Array<ApiError>}
   * @memberof RestResponseListTypedAttribute
   */
  errors?: Array<ApiError>;
}

export function RestResponseListTypedAttributeFromJSON(json: any): RestResponseListTypedAttribute {
  return RestResponseListTypedAttributeFromJSONTyped(json, false);
}

export function RestResponseListTypedAttributeFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RestResponseListTypedAttribute {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    success: !exists(json, 'success') ? undefined : json['success'],
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(TypedAttributeFromJSON),
    errors: !exists(json, 'errors') ? undefined : (json['errors'] as Array<any>).map(ApiErrorFromJSON),
  };
}

export function RestResponseListTypedAttributeToJSON(value?: RestResponseListTypedAttribute | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    success: value.success,
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(TypedAttributeToJSON),
    errors: value.errors === undefined ? undefined : (value.errors as Array<any>).map(ApiErrorToJSON),
  };
}
