/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { ApiError, ApiErrorFromJSON, ApiErrorFromJSONTyped, ApiErrorToJSON } from './';

/**
 *
 * @export
 * @interface RestResponseListString
 */
export interface RestResponseListString {
  /**
   *
   * @type {boolean}
   * @memberof RestResponseListString
   */
  success?: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof RestResponseListString
   */
  data?: Array<string>;
  /**
   *
   * @type {Array<ApiError>}
   * @memberof RestResponseListString
   */
  errors?: Array<ApiError>;
}

export function RestResponseListStringFromJSON(json: any): RestResponseListString {
  return RestResponseListStringFromJSONTyped(json, false);
}

export function RestResponseListStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestResponseListString {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    success: !exists(json, 'success') ? undefined : json['success'],
    data: !exists(json, 'data') ? undefined : json['data'],
    errors: !exists(json, 'errors') ? undefined : (json['errors'] as Array<any>).map(ApiErrorFromJSON),
  };
}

export function RestResponseListStringToJSON(value?: RestResponseListString | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    success: value.success,
    data: value.data,
    errors: value.errors === undefined ? undefined : (value.errors as Array<any>).map(ApiErrorToJSON),
  };
}
