/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ApiError,
  ApiErrorFromJSON,
  ApiErrorFromJSONTyped,
  ApiErrorToJSON,
  SubsidiaryPermission,
  SubsidiaryPermissionFromJSON,
  SubsidiaryPermissionFromJSONTyped,
  SubsidiaryPermissionToJSON,
} from './';

/**
 *
 * @export
 * @interface RestResponseCollectionSubsidiaryPermission
 */
export interface RestResponseCollectionSubsidiaryPermission {
  /**
   *
   * @type {boolean}
   * @memberof RestResponseCollectionSubsidiaryPermission
   */
  success?: boolean;
  /**
   *
   * @type {Array<SubsidiaryPermission>}
   * @memberof RestResponseCollectionSubsidiaryPermission
   */
  data?: Array<SubsidiaryPermission>;
  /**
   *
   * @type {Array<ApiError>}
   * @memberof RestResponseCollectionSubsidiaryPermission
   */
  errors?: Array<ApiError>;
}

export function RestResponseCollectionSubsidiaryPermissionFromJSON(
  json: any,
): RestResponseCollectionSubsidiaryPermission {
  return RestResponseCollectionSubsidiaryPermissionFromJSONTyped(json, false);
}

export function RestResponseCollectionSubsidiaryPermissionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RestResponseCollectionSubsidiaryPermission {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    success: !exists(json, 'success') ? undefined : json['success'],
    data: !exists(json, 'data') ? undefined : (json['data'] as Array<any>).map(SubsidiaryPermissionFromJSON),
    errors: !exists(json, 'errors') ? undefined : (json['errors'] as Array<any>).map(ApiErrorFromJSON),
  };
}

export function RestResponseCollectionSubsidiaryPermissionToJSON(
  value?: RestResponseCollectionSubsidiaryPermission | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    success: value.success,
    data: value.data === undefined ? undefined : (value.data as Array<any>).map(SubsidiaryPermissionToJSON),
    errors: value.errors === undefined ? undefined : (value.errors as Array<any>).map(ApiErrorToJSON),
  };
}
