/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  ApiError,
  ApiErrorFromJSON,
  ApiErrorFromJSONTyped,
  ApiErrorToJSON,
  ColleagueProfile,
  ColleagueProfileFromJSON,
  ColleagueProfileFromJSONTyped,
  ColleagueProfileToJSON,
} from './';

/**
 *
 * @export
 * @interface RestResponseColleagueProfile
 */
export interface RestResponseColleagueProfile {
  /**
   *
   * @type {boolean}
   * @memberof RestResponseColleagueProfile
   */
  success?: boolean;
  /**
   *
   * @type {ColleagueProfile}
   * @memberof RestResponseColleagueProfile
   */
  data?: ColleagueProfile;
  /**
   *
   * @type {Array<ApiError>}
   * @memberof RestResponseColleagueProfile
   */
  errors?: Array<ApiError>;
}

export function RestResponseColleagueProfileFromJSON(json: any): RestResponseColleagueProfile {
  return RestResponseColleagueProfileFromJSONTyped(json, false);
}

export function RestResponseColleagueProfileFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RestResponseColleagueProfile {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    success: !exists(json, 'success') ? undefined : json['success'],
    data: !exists(json, 'data') ? undefined : ColleagueProfileFromJSON(json['data']),
    errors: !exists(json, 'errors') ? undefined : (json['errors'] as Array<any>).map(ApiErrorFromJSON),
  };
}

export function RestResponseColleagueProfileToJSON(value?: RestResponseColleagueProfile | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    success: value.success,
    data: ColleagueProfileToJSON(value.data),
    errors: value.errors === undefined ? undefined : (value.errors as Array<any>).map(ApiErrorToJSON),
  };
}
