/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ServiceDates
 */
export interface ServiceDates {
  /**
   *
   * @type {Date}
   * @memberof ServiceDates
   */
  hireDate?: Date;
  /**
   *
   * @type {Date}
   * @memberof ServiceDates
   */
  leavingDate?: Date;
}

export function ServiceDatesFromJSON(json: any): ServiceDates {
  return ServiceDatesFromJSONTyped(json, false);
}

export function ServiceDatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceDates {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    hireDate: !exists(json, 'hireDate') ? undefined : new Date(json['hireDate']),
    leavingDate: !exists(json, 'leavingDate') ? undefined : new Date(json['leavingDate']),
  };
}

export function ServiceDatesToJSON(value?: ServiceDates | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    hireDate: value.hireDate === undefined ? undefined : value.hireDate.toISOString().substr(0, 10),
    leavingDate: value.leavingDate === undefined ? undefined : value.leavingDate.toISOString().substr(0, 10),
  };
}
