/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface Subsidiary
 */
export interface Subsidiary {
  /**
   *
   * @type {string}
   * @memberof Subsidiary
   */
  readonly uuid?: string;
  /**
   *
   * @type {string}
   * @memberof Subsidiary
   */
  name?: string;
}

export function SubsidiaryFromJSON(json: any): Subsidiary {
  return SubsidiaryFromJSONTyped(json, false);
}

export function SubsidiaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subsidiary {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    uuid: !exists(json, 'uuid') ? undefined : json['uuid'],
    name: !exists(json, 'name') ? undefined : json['name'],
  };
}

export function SubsidiaryToJSON(value?: Subsidiary | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
  };
}
