/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SubsidiaryPermission
 */
export interface SubsidiaryPermission {
  /**
   *
   * @type {string}
   * @memberof SubsidiaryPermission
   */
  readonly colleagueUuid?: string;
  /**
   *
   * @type {string}
   * @memberof SubsidiaryPermission
   */
  readonly subsidiaryUuid?: string;
  /**
   *
   * @type {string}
   * @memberof SubsidiaryPermission
   */
  readonly role?: SubsidiaryPermissionRoleEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum SubsidiaryPermissionRoleEnum {
  SubsidiaryManager = 'SubsidiaryManager',
}

export function SubsidiaryPermissionFromJSON(json: any): SubsidiaryPermission {
  return SubsidiaryPermissionFromJSONTyped(json, false);
}

export function SubsidiaryPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubsidiaryPermission {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    colleagueUuid: !exists(json, 'colleagueUuid') ? undefined : json['colleagueUuid'],
    subsidiaryUuid: !exists(json, 'subsidiaryUuid') ? undefined : json['subsidiaryUuid'],
    role: !exists(json, 'role') ? undefined : json['role'],
  };
}

export function SubsidiaryPermissionToJSON(value?: SubsidiaryPermission | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {};
}
