/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TypedAttribute
 */
export interface TypedAttribute {
  /**
   *
   * @type {string}
   * @memberof TypedAttribute
   */
  colleagueUuid?: string;
  /**
   *
   * @type {string}
   * @memberof TypedAttribute
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof TypedAttribute
   */
  value?: string;
  /**
   *
   * @type {string}
   * @memberof TypedAttribute
   */
  type?: TypedAttributeTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum TypedAttributeTypeEnum {
  String = 'STRING',
  Date = 'DATE',
  Number = 'NUMBER',
  Boolean = 'BOOLEAN',
}

export function TypedAttributeFromJSON(json: any): TypedAttribute {
  return TypedAttributeFromJSONTyped(json, false);
}

export function TypedAttributeFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypedAttribute {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    colleagueUuid: !exists(json, 'colleagueUuid') ? undefined : json['colleagueUuid'],
    name: !exists(json, 'name') ? undefined : json['name'],
    value: !exists(json, 'value') ? undefined : json['value'],
    type: !exists(json, 'type') ? undefined : json['type'],
  };
}

export function TypedAttributeToJSON(value?: TypedAttribute | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    colleagueUuid: value.colleagueUuid,
    name: value.name,
    value: value.value,
    type: value.type,
  };
}
