/* tslint:disable */
/* eslint-disable */
/**
 * PMA API
 * Documentation PMA API v1.0
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum UserIncludes {
  SubsidiaryPermissions = 'SUBSIDIARY_PERMISSIONS',
}

export function UserIncludesFromJSON(json: any): UserIncludes {
  return UserIncludesFromJSONTyped(json, false);
}

export function UserIncludesFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIncludes {
  return json as UserIncludes;
}

export function UserIncludesToJSON(value?: UserIncludes | null): any {
  return value as any;
}
