apiVersion: v1
kind: ConfigMap
metadata:
  name: pma-frontend-azdevops
data:
  BUILD_BUILDID: {{ .Values.azdevops.build.buildId }}
  BUILD_BUILDNUMBER: {{ .Values.azdevops.build.buildNumber }}
  BUILD_DEFINITIONNAME: {{ .Values.azdevops.build.buildDefinitionName }}
  BUILD_SOURCEBRANCHNAME: {{ .Values.azdevops.build.sourceBranchName }}
  BUILD_SOURCEBRANCH: {{ .Values.azdevops.build.sourceBranch }}
  BUILD_SOURCEVERSION: {{ .Values.azdevops.build.sourceVersion }}
  RELEASE_RELEASEID: {{ .Values.azdevops.release.releaseId }}
  RELEASE_RELEASENAME: {{ .Values.azdevops.release.releaseName }}
  RELEASE_DEFINITIONNAME: {{ .Values.azdevops.release.releaseDefinitionName }}
  RELEASE_ENVIRONMENTNAME: {{ .Values.azdevops.release.environmentName }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pma-frontend-config
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
