apiVersion: v1
kind: ConfigMap
metadata:
  name: pma-frontend-azdevops
data:
  CICD_BUILD_BUILDID: {{ .Values.azdevops.build.buildId | quote }}
  CICD_BUILD_BUILDNUMBER: {{ .Values.azdevops.build.buildNumber | quote }}
  CICD_BUILD_DEFINITIONNAME: {{ .Values.azdevops.build.buildDefinitionName | quote }}
  CICD_BUILD_SOURCEBRANCHNAME: {{ .Values.azdevops.build.sourceBranchName | quote }}
  CICD_BUILD_SOURCEBRANCH: {{ .Values.azdevops.build.sourceBranch | quote }}
  CICD_BUILD_SOURCEVERSION: {{ .Values.azdevops.build.sourceVersion | quote }}
  CICD_RELEASE_RELEASEID: {{ .Values.azdevops.release.releaseId | quote }}
  CICD_RELEASE_RELEASENAME: {{ .Values.azdevops.release.releaseName | quote }}
  CICD_RELEASE_DEFINITIONNAME: {{ .Values.azdevops.release.releaseDefinitionName | quote }}
  CICD_RELEASE_ENVIRONMENTNAME: {{ .Values.azdevops.release.environmentName | upper | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pma-frontend-config
data:
  {{- range $key, $val := .Values.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
