apiVersion: v1
kind: Secret
metadata:
  name: pma-frontend-secrets
type: Opaque
data:
  APPLICATION_COOKIE_PARSER_SECRET: {{ .Values.APPLICATION_COOKIE_PARSER_SECRET | b64enc | quote }}
  OIDC_CLIENT_ID: {{ .Values.OIDC_CLIENT_ID | b64enc | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.OIDC_CLIENT_SECRET | b64enc | quote }}
  OIDC_REFRESH_TOKEN_SECRET: {{ .Values.OIDC_REFRESH_TOKEN_SECRET | b64enc | quote }}
  IDENTITY_CLIENT_ID: {{ .Values.IDENTITY_CLIENT_ID | b64enc | quote }}
  IDENTITY_CLIENT_SECRET: {{ .Values.IDENTITY_CLIENT_SECRET | b64enc | quote }}
  IDENTITY_USER_SCOPED_TOKEN_COOKIE_SECRET: {{ .Values.IDENTITY_USER_SCOPED_TOKEN_COOKIE_SECRET | b64enc | quote }}
  