import { Status, MetaDataReport } from 'config/enum';

export const field_options = [
  { value: 'id_1', label: '2022' },
  { value: 'id_2', label: '2021' },
  { value: 'id_3', label: '2020' },
];

export const years = {
  2021: '2021',
};

export const listOfStatuses = [
  Status.APPROVED,
  Status.DRAFT,
  Status.WAITING_FOR_APPROVAL,
  Status.DECLINED,
  Status.COMPLETED,
  Status.OVERDUE,
  Status.STARTED,
  Status.NOT_STARTED,
  Status.NOT_CREATED,
];

export const metaStatuses = [
  MetaDataReport.MYR_SUBMITTED_PERCENTAGE,
  MetaDataReport.MYR_APPROVEDPERCENTAGE,
  MetaDataReport.EYR_SUBMITTED_PERCENTAGE,
  MetaDataReport.EYR_APPROVED_PERCENTAGE,
  MetaDataReport.FEEDBACK_REQUESTED_PERCENTAGE,
  MetaDataReport.FEEDBACK_GIVEN_PERCENTAGE,
  MetaDataReport.OBJECTIVE_SUBMITTED_PERCENTAGE,
  MetaDataReport.OBJECTIVES_APPROVED_PERCENTAGE,
  MetaDataReport.MYER_RATING_BREAKDONW_BELOW_EXPECTED_PERCENTAGE,
  MetaDataReport.MYR_RATING_BREAKDOWN_BELOW_EXPECTED_COUNT,
  MetaDataReport.MYR_RATING_BREAKDOWN_SATISFACTORY_PERCENTAGE,
  MetaDataReport.MYRRATING_BREAKDOWN_SATISFACTORY_COUNT,
  MetaDataReport.MYR_RATING_BREAKDOWN_GREAT_PERCENTAGE,
  MetaDataReport.MYR_RATING_BREAKDOWN_GREAT_COUNT,
  MetaDataReport.MYR_RATING_BREAKDOWN_OUTSTANDING_PERCENTAGE,
  MetaDataReport.MYR_RATING_BREAKDONW_OUTSTANDING_COUNT,
  MetaDataReport.EYR_RATING_BREAKDOWN_BELOW_EXPECTED_PERCENTAGE,
  MetaDataReport.EYR_RATING_BREAKDOWN_BELOW_EXPECTED_COUNT,
  MetaDataReport.EYR_RATING_BREAKDOWN_SATISFACTORY_PERCENTAGE,
  MetaDataReport.EYR_RATING_BREAKDOWN_SATISFACTORY_COUNT,
  MetaDataReport.EYR_RATING_BREAKDOWN_GREAT_PERCENTAGE,
  MetaDataReport.EYR_RATING_BREAKDOWN_GREAT_COUNT,
  MetaDataReport.EYR_RATING_BREAKDOWN_OUTSTANDING_PERCENTAGE,
  MetaDataReport.EYR_RATING_BREAKDOWN_OUTSTANDING_COUNT,
  MetaDataReport.NEW_TO_BUSINESS_COUNT,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_1_PERCENTAGE,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_1_COUNT,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_2_PERCENTAGE,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_2_COUNT,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_3_PERCENTAGE,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_3_COUNT,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_4_PERCENTAGE,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_4_COUNT,
];
