import { Status, MetaDataReport } from 'config/enum';

export const getFieldOptions = (currentYear) => {
  return [
    { value: (currentYear - 1).toString(), label: (currentYear - 1).toString() },
    { value: (currentYear - 2).toString(), label: (currentYear - 2).toString() },
    { value: (currentYear - 3).toString(), label: (currentYear - 3).toString() },
  ];
};

export const listOfStatuses = [
  Status.APPROVED,
  Status.DRAFT,
  Status.WAITING_FOR_APPROVAL,
  Status.DECLINED,
  Status.COMPLETED,
  Status.OVERDUE,
  Status.STARTED,
  Status.NOT_STARTED,
  Status.NOT_CREATED,
];

export const metaStatuses = [
  MetaDataReport.MYR_SUBMITTED_PERCENTAGE,
  MetaDataReport.MYR_APPROVED_PERCENTAGE,
  MetaDataReport.EYR_SUBMITTED_PERCENTAGE,
  MetaDataReport.EYR_APPROVED_PERCENTAGE,
  MetaDataReport.FEEDBACK_REQUESTED_PERCENTAGE,
  MetaDataReport.FEEDBACK_GIVEN_PERCENTAGE,
  MetaDataReport.OBJECTIVES_SUBMITTED_PERCENTAGE,
  MetaDataReport.OBJECTIVES_APPROVED_PERCENTAGE,
  MetaDataReport.MYR_RATING_BREAKDOWN_BELOW_EXPECTED_PERCENTAGE,
  MetaDataReport.MYR_RATING_BREAKDOWN_BELOW_EXPECTED_COUNT,
  MetaDataReport.MYR_RATING_BREAKDOWN_SATISFACTORY_PERCENTAGE,
  MetaDataReport.MYR_RATING_BREAKDOWN_SATISFACTORY_COUNT,
  MetaDataReport.MYR_RATING_BREAKDOWN_GREAT_PERCENTAGE,
  MetaDataReport.MYR_RATING_BREAKDOWN_GREAT_COUNT,
  MetaDataReport.MYR_RATING_BREAKDOWN_OUTSTANDING_PERCENTAGE,
  MetaDataReport.MYR_RATING_BREAKDOWN_OUTSTANDING_COUNT,
  MetaDataReport.EYR_RATING_BREAKDOWN_BELOW_EXPECTED_PERCENTAGE,
  MetaDataReport.EYR_RATING_BREAKDOWN_BELOW_EXPECTED_COUNT,
  MetaDataReport.EYR_RATING_BREAKDOWN_SATISFACTORY_PERCENTAGE,
  MetaDataReport.EYR_RATING_BREAKDOWN_SATISFACTORY_COUNT,
  MetaDataReport.EYR_RATING_BREAKDOWN_GREAT_PERCENTAGE,
  MetaDataReport.EYR_RATING_BREAKDOWN_GREAT_COUNT,
  MetaDataReport.EYR_RATING_BREAKDOWN_OUTSTANDING_PERCENTAGE,
  MetaDataReport.EYR_RATING_BREAKDOWN_OUTSTANDING_COUNT,
  MetaDataReport.NEW_TO_BUSINESS_COUNT,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_1_PERCENTAGE,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_1_COUNT,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_2_PERCENTAGE,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_2_COUNT,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_3_PERCENTAGE,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_3_COUNT,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_4_PERCENTAGE,
  MetaDataReport.ANNIVERSARY_REVIEW_PER_QUARTER_4_COUNT,
  MetaDataReport.COLLEAGUES_COUNT,
];
